<?php
/**
 * Plugin Name: Shopify → WooCommerce Importer
 * Description: Import products (and other data) from a Shopify store into WooCommerce. Includes an admin SPA and PHPUnit test scaffold.
 * Version: 1.1.0
 * Author: Generated by ChatGPT
 */

if ( ! defined( 'ABSPATH' ) ) exit;

define( 'STWI_PATH', plugin_dir_path(__FILE__) );
define( 'STWI_URL', plugin_dir_url(__FILE__) );

// Include core classes
require_once STWI_PATH . 'includes/class-auth.php';
require_once STWI_PATH . 'includes/class-shopify-api.php';
require_once STWI_PATH . 'includes/class-importer.php';

// Load settings page
require_once STWI_PATH . 'admin/settings-page.php';

// Register REST endpoints
add_action('rest_api_init', function() {
    register_rest_route('stwi/v1', '/import-products', [
        'methods'  => 'POST',
        'callback' => ['STWI_Importer', 'import_products_endpoint'],
        'permission_callback' => function() {
            return current_user_can('manage_options');
        }
    ]);
});

// Admin menu and assets
add_action('admin_menu', function() {
    add_menu_page(
        'Shopify Importer',
        'Shopify Importer',
        'manage_options',
        'stwi-importer',
        'stwi_render_app',
        'dashicons-store',
        56
    );
});

function stwi_render_app() {
    echo '<div id="stwi-root"></div>';
}

add_action('admin_enqueue_scripts', function($hook) {
    // Only load on our plugin page
    if ( ! isset($_GET['page']) || $_GET['page'] !== 'stwi-importer' ) return;

    // Settings (localize)
    $settings = [
        'rest_url' => esc_url_raw( rest_url('stwi/v1/import-products') ),
        'nonce' => wp_create_nonce('wp_rest'),
    ];
    wp_register_script('stwi-admin-app', STWI_URL . 'admin/build/main.js', [], false, true);
    wp_localize_script('stwi-admin-app', 'STWI_Settings', $settings);
    wp_enqueue_script('stwi-admin-app');

    // Simple styles
    wp_add_inline_style('stwi-admin-style', '
        #stwi-root{font-family:Arial,Helvetica,sans-serif;padding:20px;}
        .stwi-btn{background:#0073aa;color:#fff;padding:8px 12px;border-radius:4px;border:none;cursor:pointer;}
        .stwi-input{padding:6px 8px;margin:6px 0;width:100%;max-width:400px;}
        .stwi-box{margin-top:12px;padding:10px;border:1px solid #eee;border-radius:6px;background:#fff;}
    ');
});

// Activation hook: create options placeholders
register_activation_hook(__FILE__, function() {
    if ( get_option('stwi_shopify_store') === false ) {
        add_option('stwi_shopify_store', '');
    }
    if ( get_option('stwi_shopify_token') === false ) {
        add_option('stwi_shopify_token', '');
    }
});
